// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dataparser} from '../models';
import {types} from '../models';

export function ExportExcel(arg1:dataparser.Workbook):Promise<types.CommonResponse>;

export function FetchActConfig(arg1:string,arg2:string):Promise<types.CommonResponse>;

export function FetchActList(arg1:string):Promise<types.CommonResponse>;

export function GetTempAct(arg1:string,arg2:string):Promise<types.CommonResponse>;

export function ImportExcel(arg1:string,arg2:string):Promise<types.CommonResponse>;

export function KeepActionConfig(arg1:dataparser.Workbook,arg2:string):Promise<types.CommonResponse>;

export function Login(arg1:string,arg2:string):Promise<types.CommonResponse>;

export function TempActKeep(arg1:dataparser.Workbook):Promise<types.CommonResponse>;
