// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConsistentCheck(arg1) {
  return window['go']['main']['App']['ConsistentCheck'](arg1);
}

export function ConsistentSync(arg1) {
  return window['go']['main']['App']['ConsistentSync'](arg1);
}

export function ExportExcel(arg1) {
  return window['go']['main']['App']['ExportExcel'](arg1);
}

export function FetchActConfig(arg1, arg2) {
  return window['go']['main']['App']['FetchActConfig'](arg1, arg2);
}

export function FetchActList(arg1) {
  return window['go']['main']['App']['FetchActList'](arg1);
}

export function GetTempAct(arg1, arg2) {
  return window['go']['main']['App']['GetTempAct'](arg1, arg2);
}

export function ImportExcel(arg1, arg2) {
  return window['go']['main']['App']['ImportExcel'](arg1, arg2);
}

export function KeepActionConfig(arg1, arg2) {
  return window['go']['main']['App']['KeepActionConfig'](arg1, arg2);
}

export function LogError(arg1, arg2) {
  return window['go']['main']['App']['LogError'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function TempActKeep(arg1) {
  return window['go']['main']['App']['TempActKeep'](arg1);
}
